apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://stefanprodan.github.io/podinfo
    chart: podinfo
    targetRevision: 6.7.0
    helm:
      values: |
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: app.localtest.me
              paths:
                - path: /
                  pathType: ImplementationSpecific
        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
