apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.2
    helm:
      values: |
        deploymentMode: SimpleScalable
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: 2024-01-01
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          storage:
            type: filesystem
        read:
          replicas: 1
          persistence:
            enabled: false
        write:
          replicas: 1
          persistence:
            enabled: false
        backend:
          replicas: 1
          persistence:
            enabled: false
        gateway:
          enabled: true
        monitoring:
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
